//@version=6
strategy("Grid Buy/Cancel Each Bar (Lower than Prev Close)", overlay=true, default_qty_type=strategy.fixed, default_qty_value=1, margin_long=0, commission_type=strategy.commission.cash_per_contract, commission_value=43.1, slippage=2, pyramiding=100)

numGrid = input.int(5, "Number of Grid Levels", minval=1)
upperZone = input.float(title="Upper Zone", defval=750, minval=0)
lowerZone = input.float(title="Lower Zone", defval=700, minval=0)

var float gridSize = (upperZone - lowerZone) / numGrid
var float[] gridLevels = array.new_float()
var string[] buyOrderIds = array.new_string()
var array<bool> checkOrder = array.new<bool>(2 * numGrid, true)  // เก็บว่าเส้นไหนที่ซื้อไปแล้ว

// ==== สร้าง Grid ทุกวันใหม่ ====
var bool newDay = dayofmonth(time) != dayofmonth(time[1])

if newDay or barstate.isfirst
    array.clear(gridLevels)
    array.clear(buyOrderIds)

    for i = 0 to numGrid
        float level = lowerZone + (gridSize * i)
        array.push(gridLevels, level)
        array.push(buyOrderIds, "Buy_" + str.tostring(i))

        // วาดเส้น grid
        line.new(x1=bar_index, y1=level, x2=bar_index + 100, y2=level, color=color.gray, width=1, extend=extend.right, xloc=xloc.bar_time)

// ==== ยกเลิก Order ทุกแท่งใหม่ ==== 
if barstate.isnew
    for i = 0 to array.size(buyOrderIds) - 1
        strategy.cancel(array.get(buyOrderIds, i))

// ==== วาง Buy Limit ใหม่ (เฉพาะเส้นที่ต่ำกว่า close[1]) ====
for i = 0 to numGrid - 1
    float level = array.get(gridLevels, i)
    float nextLevel = array.get(gridLevels, i + 1)
    string id = array.get(buyOrderIds, i)
    string exitId = "TP_" + str.tostring(i)

    // เงื่อนไขสำคัญ: close[1] > level และ low > level ป้องกัน fill ในแท่งนี้
    if level < close[1] and low > level  and array.get(checkOrder,i) == true 
        strategy.entry(id=id, direction=strategy.long, qty=1, limit=level)
        strategy.exit(id=exitId, from_entry=id, limit=nextLevel)
        Is_sameBar = true
        array.set(checkOrder,i,false)

    // tp ให้เอาเลขเส้น grid number นั้นออกจาก  array ถ้าแตะเส้นบน เราจะเปลี่ยนเส้นล่างเป็น true เพื่อบอกว่า tp เส้นล่างแล้ว
    if not barstate.isfirst and i > 0 and high >= level
        array.set(checkOrder,i-1,true)
