// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © sirawitchchairuangsirikul

//@version=6
strategy("hi-lo 20", overlay=true, margin_long = 100)

longCondition = close > ta.highest(20)[1] // not include current bar
if (longCondition)
    strategy.entry("long", strategy.long)


shortCondition = close < ta.lowest(20)[1]
if (shortCondition)
    strategy.close("long")

