// @version=6

indicator("RSI Chart Signals", overlay=true)

// import zen library
import ZenAndTheArtOfTrading/ZenLibrary/2 as zen

// get user input
lookback = input.int(title="LookBack", defval = 7)
rsiLen = input.int(title="RSI Length", defval = 7)
rsiOB = input.float(title="RSI Overbought", defval = 80.0)
rsiOS = input.float(title="RSI Oversold", defval = 20.0)
multiplier = input.float(title="ATR Multiplier", defval = 1.0)
rr = input.float(title = "Risk Reward Ratio",defval = 1.0)

// get RSI
rsi = ta.rsi(close,rsiLen)
rsiSell = rsi > rsiOB
rsiBuy = rsi < rsiOS

// detect engulfing
bullEC = zen.isBullishEC()
bearEC = zen.isBearishEC()

// get ATR value  Average True Range (ATR) ATR คือ indicator ที่ใช้วัดความผันผวนของราคาในช่วงเวลาหนึ่ง โดยจะบอกว่า ราคามีการเคลื่อนไหว (volatility) มากน้อยแค่ไหน
atr = ta.atr(14)

// detect buy and sell signals
buySignal = (rsiBuy[1] or rsiBuy) and bullEC
sellSignal = (rsiSell[1] or rsiSell) and bearEC

// calculate stop and target
longStop = ta.lowest(low,lookback) - (multiplier * atr)
shortStop = ta.highest(high,lookback) + (multiplier * atr)
longStopDistance = close - longStop
shortStopDistance = shortStop - close
longTarget = close + (longStopDistance * rr)
shortTarget = close - (shortStopDistance * rr)

// draw data on chart
//plot(rsi,title = "RSI",color=rsiBuy? color.lime : rsiSell? color.red : color.gray, linewidth=2)
//hline(rsiOB, title = "RSI Overbought", color=color.red, linewidth=1)
//hline(rsiOS, title = "RSI Oversold", color=color.green, linewidth=1)
//bgcolor(buySignal? color.lime : sellSignal? color.red : na,title = "trade signal")
plotshape(buySignal, style = shape.triangleup,color = color.green,location = location.belowbar, size = size.small)
plotshape(sellSignal, style = shape.triangledown,color = color.red,location = location.abovebar, size = size.small)
plot(buySignal ? longStop : na, color = color.red , style = plot.style_linebr,linewidth = 2)
plot(sellSignal ? shortStop : na, color = color.red , style = plot.style_linebr,linewidth = 2)
plot(buySignal ? longTarget : na, color = color.green, style = plot.style_linebr,linewidth = 2)
plot(sellSignal ? shortTarget : na, color = color.green, style = plot.style_linebr,linewidth = 2)

// Trigger and alert
alertcondition(buySignal or sellSignal, title="RSI Signal", message="RSI Exhaustion for {{ticker}}") // ticker is EURUSD