// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © sirawitchchairuangsirikul

//@version=4
strategy("Moon Phases with EMA Strategy", overlay=true, default_qty_type=strategy.fixed, default_qty_value=1, margin_long=0, commission_type=strategy.commission.cash_per_contract, commission_value=43.1, slippage=2)
new    = input(title="New Moon Reference Date", type=input.time, defval=timestamp("2021-01-13:05:00"))
buy    = input('Full Moon',options=['New Moon','Full Moon','Higher Moon','Lower Moon'],inline='buy')
sell   = input('New Moon',options=['New Moon','Full Moon','Higher Moon','Lower Moon'],inline='sell')
longcol  = input(color.new(color.blue,80),'',inline='buy')
shortcol = input(color.new(color.white,80),'',inline='sell')
shortlen = input(14,'Short MA Length',inline='sell')
longlen  = input(50,'Long MA Length',inline='buy')

price = security(syminfo.tickerid, "15", close)
shortEMA = ema(price, shortlen)
longEMA  = ema(price, longlen)

n = bar_index
cycle = 2551442876.8992
day = 8.64e+7
diff = (new + time + day*2)%cycle/cycle

newmoon = crossover(diff,.5)
fullmoon = diff < diff[1]

plotshape(newmoon ? low : na,"New Moon",shape.labelup,location.top,na,0,text="🌑",size=size.tiny)
plotshape(fullmoon ? high : na,"Full Moon",shape.labeldown,location.bottom,na,0,text="🌕",size=size.tiny) 
plot(shortEMA,"short",color = color.yellow,linewidth=2)
plot(longEMA,"long",color = color.orange,linewidth=2)

src = close
var bool long = na
var bool short = na
if buy == 'New Moon'
    long := newmoon
else if buy == 'Full Moon'
    long := fullmoon
else if buy == 'Higher Moon'
    long := valuewhen(newmoon or fullmoon,src,0) > valuewhen(newmoon or fullmoon,src,1)
else
    long := valuewhen(newmoon or fullmoon,src,0) < valuewhen(newmoon or fullmoon,src,1)

if sell == 'New Moon'
    short := newmoon
else if sell == 'Full Moon'
    short := fullmoon
else if sell == 'Higher Moon'
    short := valuewhen(newmoon or fullmoon,src,0) > valuewhen(newmoon or fullmoon,src,1)
else
    short := valuewhen(newmoon or fullmoon,src,0) < valuewhen(newmoon or fullmoon,src,1)

longCondition = crossover(shortEMA, longEMA)
shortCondition = crossunder(shortEMA, longEMA)
var pos = 0
if long
    pos := 1
if short
    pos := -1

// clear all position if change moon phase
// if (newmoon or fullmoon) and strategy.position_size != 0
//     strategy.close_all("Moon Phase Change")

if longCondition
    if strategy.position_size != 0
        strategy.close("Short")
    strategy.entry("Long", strategy.long)
if shortCondition
    if strategy.position_size != 0
        strategy.close("Long")
    strategy.entry("Short", strategy.short)

bgcolor(pos == 1 ? longcol : shortcol)